// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZ7ix8MdFyV9moU_PVVRkROO9lljTOUY',
    appId: '1:1054448196148:web:580c40bc5e498750318861',
    messagingSenderId: '1054448196148',
    projectId: 'chat-app-f3f09',
    authDomain: 'chat-app-f3f09.firebaseapp.com',
    storageBucket: 'chat-app-f3f09.appspot.com',
    measurementId: 'G-28EY2KSSV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgGuEs5s7zhIYsimqNEUDtYh_A2D1w2aY',
    appId: '1:1054448196148:android:f79440a5c06ac5e0318861',
    messagingSenderId: '1054448196148',
    projectId: 'chat-app-f3f09',
    storageBucket: 'chat-app-f3f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB77n8Ug1uyfTz93ZwoZcuEHo_b8GhvBSY',
    appId: '1:1054448196148:ios:1e02a3ebe70bb61f318861',
    messagingSenderId: '1054448196148',
    projectId: 'chat-app-f3f09',
    storageBucket: 'chat-app-f3f09.appspot.com',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB77n8Ug1uyfTz93ZwoZcuEHo_b8GhvBSY',
    appId: '1:1054448196148:ios:1e02a3ebe70bb61f318861',
    messagingSenderId: '1054448196148',
    projectId: 'chat-app-f3f09',
    storageBucket: 'chat-app-f3f09.appspot.com',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHZ7ix8MdFyV9moU_PVVRkROO9lljTOUY',
    appId: '1:1054448196148:web:e4a22e5fe6fc7b6a318861',
    messagingSenderId: '1054448196148',
    projectId: 'chat-app-f3f09',
    authDomain: 'chat-app-f3f09.firebaseapp.com',
    storageBucket: 'chat-app-f3f09.appspot.com',
    measurementId: 'G-ZHDJB0NJ3C',
  );
}
